### ISSUE TITLE
about resource

### ISSUE THREAD

**Issue by chaiyilin** [Brigad/redux-rest-easy#19]
hi,

in the docs, it is saying:
```
const resource = {
  [actionName]: {
    // Mandatory
    method: 'GET|POST|PATCH|PUT|DELETE',
    url: string || func,
    // Optional
    beforeHook: func,
    normalizer: func,
    afterHook: func,
  },
  ...
};
```
but what if i also need to pass in some extra config for the request besides the url?

**Comment by Zephir77167** [comment]
Hey, you can pass other configs in `otherArgs` (see [action parameters](https://github.com/Brigad/redux-rest-easy/blob/master/docs/api/createResource/actions.md#properties)). It will then be available in the `beforeHook`, `normalizer`, `afterHook` and `onSuccess`.

If it doesn't meet your needs, maybe I didn't understand what you are looking to achieve, then tell me a bit more and we will find a way :)

**Comment by Titozzz** [comment]
By the way, if you need to pass specific headers in your request (auth for example), you can also have a look at [the network helpers](https://github.com/Brigad/redux-rest-easy/blob/master/docs/api/initializeNetworkHelpers.md) docs !

**Comment by Zephir77167** [comment]
I'm closing this, feel free to re-open it if you have further questions!
