### ISSUE TITLE
Error at runtime - Includes repo for reproduction

### ISSUE THREAD

**Issue by Pinesy** [Brigad/redux-rest-easy#20]
![image](https://user-images.githubusercontent.com/3433722/36807588-64d64cc2-1c91-11e8-93cf-ba20a8fea8a6.png)
/\ The error

The repo: https://github.com/Pinesy/redux-rest-easy-repro-error

I had originally tried to place redux-rest-easy into an existing small CRA project and was met with the same error. 

Node V: 9.6.1
NPM V: 5.6.0

**Comment by Zephir77167** [comment]
Hey, thanks for the feedback, and much thanks for the repo! I think it comes from the babel/rollup config, which is flawed in some way and doesn't transpile `async` functions correctly. The problem shows if you are not using babel-polyfill in your project. Our inspiration for the babel/rollup config was [the one from the redux repo]
(https://github.com/reactjs/redux/blob/master/.babelrc). Anyways, I will look into this problem and will get back to you as soon as it is fixed!

**Comment by Zephir77167** [comment]
Hey, this bug has been fixed by https://github.com/Brigad/redux-rest-easy/pull/21, and a new release is available (2.1.2). Thanks again for your help!
