### ISSUE TITLE
POST method not sending body argument to API

### ISSUE THREAD

**Issue by Pinesy** [Brigad/redux-rest-easy#32]
https://github.com/Pinesy/radical/commit/d014e4193b6d6a296a2fd593176340c67a9d11c7 is the commit where I implemented the "create and delete" product methods - the delete works fine (being passed up just an id), but for the create, i'm passing along an argument object that contains (what I believe to be) correct data. The `onSuccess` and `onError` methods work correctly. 

This is the action:
![image](https://user-images.githubusercontent.com/3433722/37216485-e10b3a70-2388-11e8-837e-fa441c252c23.png)

Would appreciate any guidance =)

**Comment by Zephir77167** [comment]
Hey, everything seems OK in your code. I tried running both your projects, but couldn't get past the login page after registering and trying to sign in. Am I missing something? Thanks!

**Comment by Pinesy** [comment]
Not quite sure, are you seeing any errors? Register/Login + Redirection to the "auth'd" page should definitely be working.

**Comment by Zephir77167** [comment]
So, I ran both projects (while having mongo running in the background). I created an account using the "pop dev vals" button, then logged in, and got the same actions as you do:

[![Screenshot from Gyazo](https://gyazo.com/dfda86e44c450ad26602c2b8a6e7386d/raw)](https://gyazo.com/dfda86e44c450ad26602c2b8a6e7386d)

But the sign in form just empties itself, and the route doesn't change.

**Comment by Pinesy** [comment]
Well you've found a bug that I've not seen! Haha. We're helping each other out! I'll poke around to see if I can re-create. Sorry about this!

**Comment by Zephir77167** [comment]
No problem, please let me know when I can test again. I have not enough time at the moment to set up minimal demos of common use cases, but it is our short term priority, so future issues will be easier to reproduce!

**Comment by Pinesy** [comment]
Alright, i'll keep trying. I haven't been able to reproduce. I'd ask for some more info from you, i.e. browser/system/etc, but I don't want to take up much more of your time trying to debug my own un-related project! I'm definitely keeping a watch on this project, though.

**Comment by Zephir77167** [comment]
It is indeed very strange, please let me know if you found out why I wasn't able to log in in your app! Else, I will set up a codesandbox to reproduce it soon so I can investigate it in depth. Also, thanks a lot for your contribution to the project!

**Comment by Pinesy** [comment]
I've hosted a version that's hooked up to the API - I tested the auth (with the login of the "pop dev vals" button) and it is working for me. https://radical-dodjlldycs.now.sh Not sure if very useful since not local, but if this works for you I would love to know! It may help diagnose the issue you are having locally.

**Comment by Zephir77167** [comment]
Hey, the link you provided works for me, but still not working in local. Very weird.

Anyways, I set up a Codesandbox higlighting your problem: https://codesandbox.io/s/ko7xm5wxy7

This is also very weird, as fetch gets called with the right headers and body. I will investigate in depth now that I have a repro case :)

**Comment by Zephir77167** [comment]
Problem fixed! For some reason, with our setup we didn't need to `JSON.stringify` the request `body`, but it is needed in other cases (including yours). You can update to 2.3.4 :)

**Comment by Pinesy** [comment]
I totally get the setup-specificness issues! Thanks for taking the time to look into that.

Weird how your project isn't working locally, but did work through the hosted version. I'll have to keep an eye on that locally. Thanks for confirming that it did work through the hosted version 👍

**Comment by Zephir77167** [comment]
No problem, thanks a lot for reporting the issue!
