### ISSUE TITLE
getResource and RECEIVE reducer assumes a wrapped response

### ISSUE THREAD

**Issue by mlabrum** [Brigad/redux-rest-easy#41]
Hey,

I've followed the sample code and modified it to point to `https://jsonplaceholder.typicode.com/users` which returns an array of users

Now running the following code
```js
const users = createResource("users")({
	retrieve: {
		method: "GET",
		url: "https://jsonplaceholder.typicode.com/users",
		afterHook: () => console.log("Users retrieved successfully")
	}
});

const Component = connect(
	state => ({
		isFetching: users.selectors.retrieve.resource.isPerforming(state),
		data: users.selectors.resource.getResource(state),
	}),
	{
		onRetrieveUsers: users.actions.retrieve.perform
	}
)(({ isFetching, data, onRetrieveUsers }) => (
	<div>
		<button onClick={onRetrieveUsers}>Fetch</button>
		<div>IsFetching: {JSON.stringify(isFetching)}</div>
		<pre>data: {JSON.stringify(data, null, 2)}</pre>
	</div>
));

// Mount component etc..
```

Will result in `users.selectors.resource.getResource(state)` returning `[]` as it can't find the `users` key under `state.restEasy.resources` as https://github.com/Brigad/redux-rest-easy/blob/master/src/internals/reducer/generateReducer/getReducerCases.js#L79 just merges the response into the `state.restEasy.resources` which results in the following state

```js
"resources": {
    "0": {
      "id": 1,
      "name": "Leanne Graham",
      "username": "Bret",
      "email": "Sincere@april.biz",
      "address": {
        "street": "Kulas Light",
        "suite": "Apt. 556",
        "city": "Gwenborough",
        "zipcode": "92998-3874",
        "geo": {
          "lat": "-37.3159",
          "lng": "81.1496"
        }
      },
      "phone": "1-770-736-8031 x56442",
      "website": "hildegard.org",
      "company": {
        "name": "Romaguera-Crona",
        "catchPhrase": "Multi-layered client-server neural-net",
        "bs": "harness real-time e-markets"
      }
    },
   ... more users ....
  },
```

Once I dug into the code I realised that I needed to add a normalizer to get the reducer placing the data in the correct location

```
const users = createResource("users")({
	retrieve: {
		method: "GET",
		url: "https://jsonplaceholder.typicode.com/users",
		afterHook: () => console.log("Users retrieved successfully"),
		normalizer: result => ({
			entities: { users: result },
			result: null
		})
	}
});
```

then the state is correctly added under `state.restEasy.resources.users`

This means that for every resource I'll need a normalizer to place it under the correct key.
I would have assumed that by creating a resource that the reducer would automatically place the data in the correct location?

Could we update the default normalizer to automatically wrap it under the resource name? Perhaps this could make this a configuration option?

Thanks

**Comment by mlabrum** [comment]
:) I now understand why you've done it this way, it might be good to document it (or maybe I missed that?) 
I've replaced my normalizer function to `normalizer: users => normalize(users, [new schema.Entity("users")])`

**Comment by Zephir77167** [comment]
Hey, it was a choice to not include default normalizers, because most of the time the defaults would be wrong (sometimes the answer is wrapped in `users`, or `user` if the request was a POST/PATCH, or not wrapped at all...). However, we wanted it to be clear how to use normalizers, and it might not be.

Documentation on createResource can be found [here](https://github.com/Brigad/redux-rest-easy/blob/master/docs/api/createResource.md#createresourceresourcename-optionsactions), and specific documentation on actions configuration can be found [here](https://github.com/Brigad/redux-rest-easy/blob/master/docs/api/createResource/actionsConfig.md). Could you please tell me how we could improve the documentation on this point? I think we need a new point of view on this one :) Thanks a lot!

**Comment by mlabrum** [comment]
Thanks :) I'll be running my team over this in the next few days and I'll
ask for suggestions. Perhaps making normalise required (even if it's set to
false) , as not having it can lead to odd bugs

**Comment by Zephir77167** [comment]
You might be right about this. I'll be waiting for your feedback, think about it until then, and will do the change if we didn't find a way to make it clearer for newcomers in the docs!

**Comment by Zephir77167** [comment]
Hey @mlabrum, have you had any feedback from your team concerning this issue?

**Comment by mlabrum** [comment]
Hey,

Sorry I thought I would have time to organise this but I'm currently on
holiday in new Zealand, returning on the 16th.

The feedback was pretty much to enforce defining a normalizer and for a
common use case perhaps including a set of normalizers that could be
imported.

I'll write up a more detailed response when I return back to Australia :)

**Comment by Zephir77167** [comment]
No worries, thanks a lot for the feedback and enjoy your vacation!

**Comment by adrienharnay** [comment]
Hey @mlabrum, how was your vacation?

We are still open for enforcing `normalizer`, please let me know if you have more info for us to work with, when you have time!

**Comment by adrienharnay** [comment]
Hey, long time no see! Have you had some time to think about this? We've had the same feedback from several people, so if you don't have any new elements we will just make `normalizer` required :)

**Comment by adrienharnay** [comment]
Closing for now, feel free to reopen if you have more feedback on this
