### ISSUE TITLE
Recommended way to reset error status

### ISSUE THREAD

**Issue by p21asthana** [Brigad/redux-rest-easy#45]
What is the recommended way to reset the error status once the error has been displayed on the screen. Should we have our own way to keep the track of this?

**Comment by Zephir77167** [comment]
Hey, thanks for your interest in redux-rest-eady!

When a request fails, the [hasFailed selector](https://github.com/Brigad/redux-rest-easy/blob/master/docs/api/createResource/selectors.md#hasfailedstate-ownprops-bool) sill return `true`. Your component can then display the error to the user, and provide them a way to retry (or retry automatically). When the request will have performed successfully, `hasFailed` will return `false`.

Please reopen this issue if something isn't clear or if you have more questions!

**Comment by Zephir77167** [comment]
I think I would handle this at the component-level yes, something like

```
class ComponentWithError extends Component {
  state = {
    failedMultipleTimes: false,
  };

  componentDidUpdate(prevProps) {
    this.setState(() =>
      prevProps.hasFailed && this.props.hasFailed ?
        {
          failedMultipleTimes: true,
        }
        : null
    );
  }

  render() {
    if (this.state.failedMultipleTimes) {
		return 'Maybe you should stop trying...'
    }

    if (this.props.hasFailed) {
      return 'Request has failed. Try again?'
    }

    return 'Yay!'
  }
}

ComponentWithError.propTypes = {
  hasFailed: PropTypes.bool.isRequired,
};
```

**Comment by p21asthana** [comment]
See that's the problem with this approach. It's not scalable, if this is id
specific, I will have to create multiple state variables.

Is there a way to add app specific variable in store?

**Comment by Zephir77167** [comment]
You can always make use of the `onError` callback at the component-level to dispatch a specific action.

Redux-rest-easy aims to solve common pain points with Redux and REST APIs, and provides handlers so you can always adapt to your specific use case :)
