### ISSUE TITLE
How to retrieve errors from backend

### ISSUE THREAD

**Issue by ddzwigaj** [Brigad/redux-rest-easy#76]
when using from example

` 
onError = (error) => {
    console.log('Failed with error: ', error)
    this.setState({ error: true });
  };
`

i was expecting to retrieve json with errors from my backend:

`
{
    "username": [
        "This field is required."
    ],
    "password": [
        "This field is required."
    ]
}
`

to display them accordingly if its missing credentials or wrong credentials, but instead i got json with request headers

`
Failed with error:  {"response":{"type":"default","status":400,"ok":false,"headers":{"map":{"server":"WSGIServer/0.2 CPython/3.5.2","content-type":"application/json","x-frame-options":"SAMEORIGIN","allow":"POST, OPTIONS","date":"Thu, 25 Jul 2019 21:41:29 GMT","vary":"Cookie","content-length":"68"}},"url":"http://my-backend-ip/token/","_bodyInit":{"_data":{"size":68,"offset":0,"blobId":"EA9F3715-C076-4B97-9650-59984B1FF548","type":"application/json","name":"token"}},"_bodyBlob":{"_data":{"size":68,"offset":0,"blobId":"EA9F3715-C076-4B97-9650-59984B1FF548","type":"application/json","name":"token"}},"bodyUsed":true},"line":157338,"column":30,"sourceURL":"http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false"}
`

how to achievie this?

**Comment by adrienharnay** [comment]
Hey,

I think `error.response.json()` is what you're after 🙂

Please reopen the issue if it doesn't work!

**Comment by ddzwigaj** [comment]
@adrienharnay error.response.json() is undefined

**Comment by adrienharnay** [comment]
It _might_ be `error.json()`, it depends on the function throwing the Error. See [here](https://brigad.gitbook.io/redux-rest-easy/docs/api/initializenetworkhelpers#example) for a full working example of network helpers (`handleStatusCode` and `handleError`).
