### ISSUE TITLE
How to add meta offline params to actions?

### ISSUE THREAD

**Issue by dpellier** [Brigad/redux-rest-easy#80]
Hi, I'm currently trying to add offline support to a react-native application.

For that, I saw in the doc your examples about how to configure the store to make redux-rest-easy work well with redux-offline.

What I don't understand, is how do you define the offline meta information for each action (effect, commit, rollback)?
In redux-offline doc, defining this is done on the action creation like:
```
const followUser = userId => ({
    type: 'FOLLOW_USER_REQUEST',
    payload: { userId },
    meta: {
        offline: {
            // the network action to execute:
            effect: { url: '/api/follow', method: 'POST', json: { userId } },
            // action to dispatch when effect succeeds:
            commit: { type: 'FOLLOW_USER_COMMIT', meta: { userId } },
            // action to dispatch if network action fails permanently:
            rollback: { type: 'FOLLOW_USER_ROLLBACK', meta: { userId } }
        }
    }
});
```

But where can I define those when declaring rest-easy actions like:
```
const formResource = createResource(formKey)({
    fetch: {
        method: 'GET',
        url: `${API.FORM_URL}/questionform/:name`,
        normalizer: (response) => normalize(response, formSchema)
    },
    submit: {
        method: 'POST',
        url: `${API.FORM_URL}/answer`
    },
    ...
});

const {
    actions: {
        fetch: { perform: fetchForm },
        submit: { perform: submitForm },
        ...
    }
};
```

I know this not really an issue with the lib, but I'm quite of struggling with that and would really appreciate any help.
Thanks

**Comment by dpellier** [comment]
Or maybe the correct question would just be, how can I trigger the success callback of an action when offline, instead of a `Network Request Error`?

```
// How to get the onSuccess called while offline?
submit: (onSuccess) => dispatch(submit({ onSuccess }))
```

My current env:
```
@brigad/redux-rest-easy: 4.0.1
@redux-offline/redux-offline: 2.5.2-native.3
redux: 4.0.4
redux-logger: 3.0.6
redux-persist: 4.10.2
redux-thunk: 2.3.0
...
```

I really do want to keep using this lib with the offline feature, but I couldn't find much info on how to use it correctly.

**Comment by adrienharnay** [comment]
Hey, to be honest I have only used redux-offline for the cache persistence, but I will be happy to help you achieve what you're trying to do!

Since I'm not as familiar with redux-offline as you are, I might be wrong, but I would suggest using [custom networkHelpers](https://brigad.gitbook.io/redux-rest-easy/docs/api/initializenetworkhelpers) to handle the error as you need to. Maybe you won't have the right data available in `handleStatusCode` / `handleError` contexts
, but we could add it if it makes sense 🙂

**Comment by dpellier** [comment]
Thanks.

I'm trying to go step by step, so first I've tried to add redux-persist only, with a store like that:
```
const persistConfig = {
    key: 'app',
    storage: AsyncStorage,
    blacklist: ['connectivityReducer']
};
const persistedReducer = persistReducer(persistConfig, rootReducer);

export const store = createStore( persistedReducer, applyMiddleware(thunk, logger));
export const persistor = persistStore(store);
```
=> This configuration works fine, everything is persisted and hydrated.

So I've tried to add the redux-rest-easy transform:
```
function inbound(state) {
    return getPersistableState(state, {
        persist: {
            alwaysPersist: ['locale', 'translation', 'login'],
            neverPersist: []
        }
    });
}

const restEasyTransform = createTransform(inbound, null, { whitelist: ['restEasy'] });

const persistConfig = {
    key: 'app',
    storage: AsyncStorage,
    blacklist: ['connectivityReducer'],
    transforms: [restEasyTransform]
};
const persistedReducer = persistReducer(persistConfig, rootReducer);

export const store = createStore( persistedReducer, applyMiddleware(thunk, logger));
export const persistor = persistStore(store);
```
=> Then nothing is saved anymore.
`getPersistableState` always returns empty objects
```
requests: {}
resources: {}
resolversHashes: {requests: {…}, resources: {…}}
```

Any ideas what I'm doing wrong already?

**Comment by dpellier** [comment]
Ok seems the problem here was just the `persist` key in the getPersistableState second argument which is not necessary.

This doc seems to be outdated then https://github.com/Brigad/redux-rest-easy/blob/master/docs/api/getPersistableState.md

**Comment by dpellier** [comment]
@adrienharnay I've tried as you recommended using networkHelpers.

So my resource will test on error if online and if it's the case, store the request to retry it when connected again. But the info about the initial request are not available here.
```
const formResource = createResource(formKey)({
    submit: {
        method: 'POST',
        url: `${API.FORM_URL}/answer`,
        networkHelpers: {
            handleError: (error, dispatch) => {
                return testConnection().then((isOnline) => {
                    if (isOnline) {
                        throw error;
                    } else {
                        dispatch(saveOfflineRequests(??))  // I don't have the initial request here
                    }
                });
            }
        }
    }
});
```

Another possibility was to add a very simple custom middleware that check if action is a rest-easy request and store it if the application is online.
```
function offlineMiddleware({ dispatch, getState }) {
    return (next) => action => {
        if (/^@@rest-easy.*REQUEST$/.test(action.type) && !getState().connectivityReducer.isOnline) {
            return saveRequest(action)(dispatch);     // thunk action
        }

        return next(action);
    };
}
```
In that case I can store correctly all data.
But the issue with both solution is that the request is actually performed anyway, which means the `@@rest-easy/form/dummy/FAIL` action is dispatched and the `onError` callback of the initial action is called.
But in an offline situation, I want to be able to call the `onSuccess` callback.
Plus it would be nice to avoid the request to be send.

Then I thought about using the `beforeHook` to check connectivity, store the action, prevent the request and call the right callback.
But it seems you can't cancel an action in the hook, plus `onSuccess` and `onError` callback are not passed to the hook either.

What is you opinion on those solutions, am I missing something? Is there a better alternative you may think of?

**Comment by adrienharnay** [comment]
Hey, sorry I've been quiet, I'm in a middle of moving to a new house.

Maybe we could add a new entry to the `networkHelpers` configuration? It could be something like `performRequest`, which by default would be set to `(...args) => fetch(...args)`, but could be changed to `(...args) => axios(...args)`, or even in your case

```
if (args.something !== something) {
  fetch(...args);
} else {
  // don't perform request
}
```

What do you think?

**Comment by dpellier** [comment]
Hi, sorry we finally decided to remove the lib and manage it manually.
